# Generated by Django 4.0.6 on 2022-07-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='name',
            field=models.CharField(default='Lioncat', max_length=200),
            preserve_default=False,
        ),
    ]
